### PR TITLE
Fix issue with not being able to set a validation context

### PR DESCRIPTION
**Pull request by sirwolfgang**
This is a change for [Rails 5 support](http://blog.bigbinary.com/2016/04/08/validate-multiple-contexts-in-rails-5.html). I am not familiar enough with this test framework to properly spec this. Tested working locally via implementing project.

### CODE REVIEW

**Comment by schneems** [comment]
Restarting tests

**Comment by javiercr** [comment]
Is there any chance to get this merged? IMHO it makes a lot of sense, as partial validation using contexts is quite handy for wizard forms.

**Comment by schneems** [comment]
Tests are still failing. 

```
Error: test_redirect_from_last_step_to_root_path(UpdatesControllerTest): ArgumentError: wrong number of arguments (1 for 0)
app/controllers/updates_controller.rb:5:in `save'
```

**Comment by schneems** [comment]
Ahh, I figured out why it's failing. Because the `save` for that object does not take arguments. Before passing in arguments, we can first check arity of the method

```
if method(:save).arity >= 1
```

Are you still interested in getting this change merged in? Can you also add a note to the readme about this?

**Comment by sirwolfgang** [comment]
@schneems Updated, and passing.

**Comment by schneems** [comment]
Thanks! Released in version 1.3.3

**Pull request merged**
