### PR TITLE
Uses Rails autoloading to expose WizardController.

### LINKED ISSUE #185: Is there a way to stop the gem requiring the app directory? (I'm using a Rails engine)
I'm using `wicked` as part of my own engine. That engine is used in a Rails app with a component architecture instead of a top-level `app` directory ([here's an example](https://github.com/shageman/the_next_big_thing)). That means I don't have a top-level `ApplicationController`.

The app works in development, but when I deploy, I get the following stack trace:

```
../gems/wicked-1.0.3/app/controllers/wicked/wizard_controller.rb:5:in `<top (required)>': uninitialized constant ApplicationController (NameError)
```

Is there a way I can stop the gem requiring the `app` directory in production?

### PR DESCRIPTION
**Pull request by aaronmcadam**
Fixes #185.

This change allows other engines without top-level `ApplicationController`s to work

### CODE REVIEW

**Comment by schneems** [comment]
Looks good to me, thanks :heart:

**Comment by aaronmcadam** [comment]
Ah, thanks for the tips :+1:

**Comment by aaronmcadam** [comment]
@schneems Sorry to be a pain, but when do you reckon the next release will be? I'm using a copy of my fork on our gem server for now.

**Comment by schneems** [comment]
Running tests on master for 1.2.1 on travis. Having some problems with appraisals.

**Comment by schneems** [comment]
1.2.1 is pushed

**Comment by aaronmcadam** [comment]
Thanks a lot dude! :heart:

**Pull request merged**
