### PR TITLE
allow super index to be called

### PR DESCRIPTION
**Pull request by arthurtalkgoal**

### CODE REVIEW

**Comment by schneems** [comment]
I'm generally :-1: on inheriting controller code for public facing route options i.e. show, index, etc. This will fail if there's any kind of render or redirect in the other index action (double redirect error). 

Tests are failing. What's your use case here?

**Comment by arthurtalkgoal** [comment]
Hi @schneems , 

The inherited ```def index ``` making it impossible to use the wick in the existing controllers. it is very troublesome. All the other methods are very well.

I will fix the Travis, the codes is fine in my local controllers which has ```def index```

**Comment by schneems** [comment]
> making it impossible to use the wick in the existing controllers. it is very troublesome

What is your specific use case? What are you trying to do? What action exists in the index action you're trying to inherit?

**Comment by arthurtalkgoal** [comment]
I override other plugins setup to step by step.   One is spree.

The spree admin countries use index method.

And using the index, edit, update show method name usually got conflict with other gems.   If it is configureable or use some specific names
, then the stepbystep flow can be merged with most other controllers
Arthur CHAN

Co-founder
Talkgoal.com

**Comment by schneems** [comment]
This is the first time i've seen wicked breaking an inherited controller method in the ~3 years it's been around. I'm not convinced it's a use case we should be catering to. You can get around this already with metaprogramming.

Something like:

```ruby
class MyController < SpreeController::Foo

  alias_method :index_without_wicked :index
  include Wicked::Wizard

  def index
    index_without_wicked
  end
end
```

Should get you what you need. It's too error prone to call super in the wicked index since we don't have a good idea of what that method would be doing.

**Comment by arthurtalkgoal** [comment]
Hi @schneems,

Thanks for the comments,

First off, after reading your comments, my new commit didn't call the ```super ``` but use ```wizard_index``` in wicked instead.

https://github.com/arthurtalkgoal/wicked/commit/2de547c40061da4db73cdae2cb79731f2ac41356

My use case is simple make existing Registration or Configuration into stepbystep by putting decorators the ```include Wicked concerns```; isn't it more powerful? With merely CSS  , I am able to do such stepbystep.

The only challenge is fixed by able to rename the ```index``` to ```wizard_index```; which I think there is no good reason why ```index``` and ```show``` should be preserved for wicked all the time.

spree

countries

**Pull request closed without merging**
