### PR TITLE
Updates for rails5 and deprecation notices

### PR DESCRIPTION
**Pull request by twalpole**
If you're willing to drop rails < 4 support from the next release the before_filter/action  stuff can be cleaned up

### CODE REVIEW

**Comment by schneems** [comment]
I'm actually thinking of monkey patching `before_filter` and friends to call out to `before_*` that would probably be easier. We can check to see if `before_filter` is a defined method and optionally define it.

**Comment by twalpole** [comment]
I thought about that, but then decided against it due to that potentially affecting other projects that might detect for the presence/lack of presence of it for behavior changes - I don't know of any that do, maybe just overly cautious

**Comment by schneems** [comment]
In this case I think it's fine. There's essentially no behavior change, just a change in name. If we were careful we could define the method only on the controller that wicked is merged into. That would probably be the safest.

**Comment by twalpole** [comment]
@schneems I changed this to add needed *_action methods to a controller when not defined - hows  this?

**Comment by schneems** [comment]
I was actually thinking of going the other way. defining before_filter if it's not defined. This works though, guess it encourages upgrading and encourages us to use the currently maintained API. Thanks for your work here!

**Comment by schneems** [comment]
1.3.0 is released.

**Pull request merged**
